# Generated by Django 4.2.17 on 2024-12-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_messages', '0002_whatsappuser_receivedwhatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='name',
            field=models.CharField(default='Unknown user', max_length=100),
        ),
    ]
